# copied and adapted from:
# https://gitlab.com/SystemSlayerOfficial/gitlab-ci-series/-/blob/Gitlab_CI_Series_EP03/.gitlab-ci.yml
#
#
# Environment variable readme
# https://docs.gitlab.com/ee/ci/variables/

# Predefined environment variables
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

# Using docker images
# https://docs.gitlab.com/ee/ci/docker/using_docker_images.html

# .gitlab-ci.yml reference
# https://docs.gitlab.com/ee/ci/yaml/

# Container registry reference (authenticating, etc.)
# https://gitlab.com/help/user/packages/container_registry/index

stages:
  - test

docker-development-test:
  # Job that handles both building and testing in a single stage. This is used to test commits against
  # all branches except master. This job combines building and testing in order to save time.
  # Since no pushing/pulling of images is needed, no variables are defined. docker-compose.yml is setup
  # to use a default value for the image tag when COMPOSE_TAG is not defined in the current environment.

  except:
    - master

  image: tmaier/docker-compose

  services:
    - docker:dind

  stage: test

  # builds image before running 'script'
  before_script:
    - docker-compose build --no-cache

  # command that will decide whether pipeline did fail or succeed
  script:
    - docker-compose run nuxt-client ./nuxt-client/test.sh


