version: "3.8"

services:
    nuxt-client:
        # names the resulting image
        image: ${CI_REGISTRY_IMAGE}:latest
        volumes:
            # used to build the client
            - ./nuxt-client:/nuxt-client
            - ./.pipeline-scripts:/pipeline-scripts
            # mounted directory where pm2 will listen on file changes and auto
            # reload the deployment :]
            - /deploy:/deploy
