version: "3.8"

services:
    nuxt-client:
        # names the resulting image
        image: ${CI_REGISTRY_IMAGE}:latest
        # how to build image if it is not in the registry.
        build:
            context: .
            dockerfile: nuxt-client-dockerfile
        # makes nuxt-client folder available in container
        volumes:
            # used to build the client
            - ./nuxt-client:/nuxt-client
            - ./.pipeline-scripts:/pipeline-scripts
            # mounted directory where pm2 will listen on file changes and auto
            # reload the deployment :]
            - /deploy:/deploy
            - /etc/ssl/certs:/etc/ssl/certs
