version: "3.8"

services:
    nuxt-client:
        # name of our resulting image
        image: nuxt-client
        # how to build if image non existant
        build:
            context: .
            dockerfile: nuxt-client-dockerfile
        # mounts the magic-tiles folder in our repo to the folder /nuxt-client
        # inside our container.
        # looks like we cant mount stuff with docker inside docker
        # volumes:
        #     - ./:/nuxt-client
